server:
    port: 7070

spring:
    application:
        name: ms-customer
    rabbitmq:
        host: sparrow-01.rmq.cloudamqp.com
        port: 5672
        username: iacqclnc
        password: U4Yq-a0t_9p3fZSDvwuzFJzMyhD-4CvN
        virtual-host: iacqclnc
    zipkin:
        enabled: false
        locator:
            discovery:
                enabled: false

eureka:
    client:
        registerWithEureka: true
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/
        enabled: false